import { Meals, FreshFood, Grains, Sauce, Drinks, Canned, Soaps, Utensils, Stationery } from "../public/svg/CategoriesSvg/svg";

export const Cats: CategoriesType[] = [
    { name: 'Meals', icon: Meals },
    { name: 'Fresh Food', icon: FreshFood },
    { name: 'Grains', icon: Grains },
    { name: 'Sauces', icon: Sauce },
    { name: 'Drinks', icon: Drinks },
    { name: 'Canned', icon: Canned },
    { name: 'Toiletries', icon: Soaps },
    { name: 'Kitchen', icon: Utensils },
    { name: 'Stationery', icon: Stationery },
];



export const DEMO_PRODUCTS: ProductCardProps[] = [
  { name: "Egusi (Melon Seeds)", category: "Meals", price: 3500, imageURL: "/assets/Untitled design.png", more: "Per kg", wishlisted: true},
  { name: "Garri (White)", category: "Meals", price: 2500, imageURL: "/assets/Untitled design.png", more: "Per kg" },
  { name: "Garri (Yellow)", category: "Meals", price: 2700, imageURL: "/assets/Untitled design.png", more: "Per kg" },
  { name: "Ogbono (Dried)", category: "Meals", price: 4000, imageURL: "/assets/Untitled design.png", more: "Per kg", wishlisted: true },
  { name: "Palm Oil", category: "Sauces", price: 3200, imageURL: "/assets/Untitled design.png", more: "Per bottle" },
  { name: "Groundnut Oil", category: "Sauces", price: 3800, imageURL: "/assets/Untitled design.png", more: "Per bottle" },
  { name: "Long Grain Rice", category: "Meals", price: 5200, imageURL: "/assets/Untitled design.png", more: "Per kg", wishlisted: true },
  { name: "Ofada Rice", category: "Meals", price: 5800, imageURL: "/assets/Untitled design.png", more: "Per kg" },
  { name: "Honey Beans (Oloyin)", category: "Meals", price: 4500, imageURL: "/assets/Untitled design.png", more: "Per kg", wishlisted: true },
  { name: "Dried Stockfish", category: "Meals", price: 8500, imageURL: "/assets/Untitled design.png", more: "Per kg" },
  { name: "Smoked Catfish", category: "Fresh Food", price: 6000, imageURL: "/assets/Untitled design.png", more: "Per kg" },
];

export const CARTPRODUCTS = [
    {
        productName : 'Egusi(melon seeds)',
        img : '/assets/cornflakes.jpg',
        meta: 'Per Derica',
        quantity: 2,
        price: 300,
    },
    {
        productName : 'Egusi(melon seeds)',
        img : '/assets/cornflakes.jpg',
        meta: 'Per Derica',
        quantity: 4,
        price: 300,
    },
]

export const MOCK_ORDERS: OrderProperties[] = [
  {
    orderId: "ORD-001",
    date: "2026-01-15",
    status: "successful",
    items: [
      { id: "1", name: "Egusi (Melon Seeds)", quantity: 2, unit: "Per kg", price: 3500, image: "/assets/productPlaceholder.png" },
      { id: "4", name: "Ogbono (Dried)", quantity: 1, unit: "Per kg", price: 4000, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 11000,
    agentFee: 500,
    deliveryFee: 1500,
    total: 13000,
    payment: { method: "Mastercard", maskedCard: "******4832" },
    delivery: { method: "Ojarun delivery", address: "42 Allen Avenue, Ikeja, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-002",
    date: "2026-01-20",
    status: "successful",
    items: [
      { id: "7", name: "Long Grain Rice", quantity: 3, unit: "Per kg", price: 5200, image: "/assets/productPlaceholder.png" },
      { id: "6", name: "Groundnut Oil", quantity: 2, unit: "Per bottle", price: 3800, image: "/assets/productPlaceholder.png" },
      { id: "17", name: "Peak Milk", quantity: 1, unit: "Per carton", price: 4500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 27700,
    agentFee: 800,
    deliveryFee: 2000,
    total: 30500,
    payment: { method: "Visa", maskedCard: "******7912" },
    delivery: { method: "Ojarun delivery", address: "15 Awolowo Road, Ikoyi, Lagos", estimatedTime: "25 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-003",
    date: "2026-02-03",
    status: "successful",
    items: [
      { id: "13", name: "Yam Tubers", quantity: 4, unit: "Per tuber", price: 2800, image: "/assets/productPlaceholder.png" },
      { id: "14", name: "Sweet Potatoes", quantity: 2, unit: "Per kg", price: 2200, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 15600,
    agentFee: 600,
    deliveryFee: 1800,
    total: 18000,
    payment: { method: "Cash" },
    delivery: { method: "Ojarun delivery", address: "7 Bode Thomas Street, Surulere, Lagos", estimatedTime: "30 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Mile 12 Market",
  },
  {
    orderId: "ORD-004",
    date: "2026-02-14",
    status: "successful",
    items: [
      { id: "5", name: "Palm Oil", quantity: 3, unit: "Per bottle", price: 3200, image: "/assets/productPlaceholder.png" },
      { id: "20", name: "Tomato Paste", quantity: 5, unit: "Per pack", price: 1500, image: "/assets/productPlaceholder.png" },
      { id: "19", name: "Salted Butter", quantity: 2, unit: "Per pack", price: 2500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 22100,
    agentFee: 1000,
    deliveryFee: 2500,
    total: 25600,
    payment: { method: "Mastercard", maskedCard: "******2154" },
    delivery: { method: "Ojarun delivery", address: "23 Adeniran Ogunsanya Street, Surulere, Lagos", estimatedTime: "15 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-005",
    date: "2026-03-01",
    status: "successful",
    items: [
      { id: "2", name: "Garri (White)", quantity: 5, unit: "Per kg", price: 2500, image: "/assets/productPlaceholder.png" },
      { id: "9", name: "Honey Beans (Oloyin)", quantity: 2, unit: "Per kg", price: 4500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 21500,
    agentFee: 700,
    deliveryFee: 1500,
    total: 23700,
    payment: { method: "Wallet" },
    delivery: { method: "Ojarun delivery", address: "10 Opebi Road, Ikeja, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-006",
    date: "2026-03-12",
    status: "successful",
    items: [
      { id: "11", name: "Smoked Catfish", quantity: 3, unit: "Per kg", price: 6000, image: "/assets/productPlaceholder.png" },
      { id: "12", name: "Dried Crayfish", quantity: 2, unit: "Per kg", price: 3500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 25000,
    agentFee: 1200,
    deliveryFee: 2000,
    total: 28200,
    payment: { method: "Visa", maskedCard: "******6357" },
    delivery: { method: "Ojarun delivery", address: "5 Norman Williams Street, Ikoyi, Lagos", estimatedTime: "25 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Bodija Market",
  },
  {
    orderId: "ORD-007",
    date: "2026-03-28",
    status: "successful",
    items: [
      { id: "15", name: "Corn Flakes", quantity: 4, unit: "Per pack", price: 1800, image: "/assets/productPlaceholder.png" },
      { id: "16", name: "Milo (Tinned)", quantity: 2, unit: "Per tin", price: 3200, image: "/assets/productPlaceholder.png" },
      { id: "3", name: "Garri (Yellow)", quantity: 1, unit: "Per kg", price: 2700, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 16300,
    agentFee: 500,
    deliveryFee: 1000,
    total: 17800,
    payment: { method: "Cash" },
    delivery: { method: "Ojarun delivery", address: "81 Toyin Street, Ikeja, Lagos", estimatedTime: "15 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-008",
    date: "2026-04-05",
    status: "successful",
    items: [
      { id: "10", name: "Dried Stockfish", quantity: 2, unit: "Per kg", price: 8500, image: "/assets/productPlaceholder.png" },
      { id: "18", name: "Raw Groundnuts", quantity: 3, unit: "Per kg", price: 2000, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 23000,
    agentFee: 1500,
    deliveryFee: 3000,
    total: 27500,
    payment: { method: "Mastercard", maskedCard: "******9048" },
    delivery: { method: "Ojarun delivery", address: "12 Adeniji Adele Road, Lagos Island", estimatedTime: "35 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: true },
    market: "Mile 12 Market",
  },
  {
    orderId: "ORD-009",
    date: "2026-04-10",
    status: "in progress",
    items: [
      { id: "8", name: "Ofada Rice", quantity: 2, unit: "Per kg", price: 5800, image: "/assets/productPlaceholder.png" },
      { id: "5", name: "Palm Oil", quantity: 1, unit: "Per bottle", price: 3200, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 14800,
    agentFee: 600,
    deliveryFee: 1500,
    total: 16900,
    payment: { method: "Wallet" },
    delivery: { method: "Ojarun delivery", address: "34 Mobolaji Bank Anthony Way, Ikeja, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-010",
    date: "2026-04-18",
    status: "in progress",
    items: [
      { id: "1", name: "Egusi (Melon Seeds)", quantity: 3, unit: "Per kg", price: 3500, image: "/assets/productPlaceholder.png" },
      { id: "20", name: "Tomato Paste", quantity: 4, unit: "Per pack", price: 1500, image: "/assets/productPlaceholder.png" },
      { id: "12", name: "Dried Crayfish", quantity: 1, unit: "Per kg", price: 3500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 20000,
    agentFee: 800,
    deliveryFee: 2000,
    total: 22800,
    payment: { method: "Visa", maskedCard: "******3127" },
    delivery: { method: "Ojarun delivery", address: "55 Raymond Njoku Street, Ikoyi, Lagos", estimatedTime: "25 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-011",
    date: "2026-04-25",
    status: "in progress",
    items: [
      { id: "13", name: "Yam Tubers", quantity: 6, unit: "Per tuber", price: 2800, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 16800,
    agentFee: 500,
    deliveryFee: 2500,
    total: 19800,
    payment: { method: "Cash" },
    delivery: { method: "Ojarun delivery", address: "9 Simbiat Abiola Way, Ikeja, Lagos", estimatedTime: "30 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: false },
    market: "Mile 12 Market",
  },
  {
    orderId: "ORD-012",
    date: "2026-05-02",
    status: "in progress",
    items: [
      { id: "7", name: "Long Grain Rice", quantity: 5, unit: "Per kg", price: 5200, image: "/assets/productPlaceholder.png" },
      { id: "9", name: "Honey Beans (Oloyin)", quantity: 3, unit: "Per kg", price: 4500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 39500,
    agentFee: 1200,
    deliveryFee: 2000,
    total: 42700,
    payment: { method: "Mastercard", maskedCard: "******5561" },
    delivery: { method: "Ojarun delivery", address: "22 Kofo Abayomi Street, Victoria Island, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-013",
    date: "2026-05-08",
    status: "in progress",
    items: [
      { id: "16", name: "Milo (Tinned)", quantity: 3, unit: "Per tin", price: 3200, image: "/assets/productPlaceholder.png" },
      { id: "17", name: "Peak Milk", quantity: 2, unit: "Per carton", price: 4500, image: "/assets/productPlaceholder.png" },
      { id: "15", name: "Corn Flakes", quantity: 2, unit: "Per pack", price: 1800, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 22200,
    agentFee: 700,
    deliveryFee: 1500,
    total: 24400,
    payment: { method: "Wallet" },
    delivery: { method: "Ojarun delivery", address: "3 Ikorodu Road, Maryland, Lagos", estimatedTime: "25 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-014",
    date: "2026-05-15",
    status: "in progress",
    items: [
      { id: "11", name: "Smoked Catfish", quantity: 2, unit: "Per kg", price: 6000, image: "/assets/productPlaceholder.png" },
      { id: "18", name: "Raw Groundnuts", quantity: 4, unit: "Per kg", price: 2000, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 20000,
    agentFee: 900,
    deliveryFee: 1800,
    total: 22700,
    payment: { method: "Mastercard", maskedCard: "******8734" },
    delivery: { method: "Ojarun delivery", address: "17 Ahmadu Bello Way, Victoria Island, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: true, delivered: false },
    market: "Bodija Market",
  },
  {
    orderId: "ORD-015",
    date: "2026-05-22",
    status: "in progress",
    items: [
      { id: "2", name: "Garri (White)", quantity: 4, unit: "Per kg", price: 2500, image: "/assets/productPlaceholder.png" },
      { id: "6", name: "Groundnut Oil", quantity: 1, unit: "Per bottle", price: 3800, image: "/assets/productPlaceholder.png" },
      { id: "4", name: "Ogbono (Dried)", quantity: 2, unit: "Per kg", price: 4000, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 21800,
    agentFee: 800,
    deliveryFee: 2000,
    total: 24600,
    payment: { method: "Visa", maskedCard: "******4290" },
    delivery: { method: "Ojarun delivery", address: "28 Akanni Doherty Street, Ikeja, Lagos", estimatedTime: "15 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: true, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-016",
    date: "2026-05-30",
    status: "in progress",
    items: [
      { id: "19", name: "Salted Butter", quantity: 3, unit: "Per pack", price: 2500, image: "/assets/productPlaceholder.png" },
      { id: "14", name: "Sweet Potatoes", quantity: 3, unit: "Per kg", price: 2200, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 14100,
    agentFee: 600,
    deliveryFee: 1500,
    total: 16200,
    payment: { method: "Cash" },
    delivery: { method: "Ojarun delivery", address: "6 Isaac John Street, Ikeja, Lagos", estimatedTime: "30 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-017",
    date: "2026-02-10",
    status: "failed",
    items: [
      { id: "8", name: "Ofada Rice", quantity: 2, unit: "Per kg", price: 5800, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 11600,
    agentFee: 0,
    deliveryFee: 0,
    total: 11600,
    payment: { method: "Mastercard", maskedCard: "******3421" },
    delivery: { method: "Ojarun delivery", address: "44 Adenuga Street, Surulere, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-018",
    date: "2026-03-05",
    status: "failed",
    items: [
      { id: "3", name: "Garri (Yellow)", quantity: 3, unit: "Per kg", price: 2700, image: "/assets/productPlaceholder.png" },
      { id: "10", name: "Dried Stockfish", quantity: 1, unit: "Per kg", price: 8500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 16600,
    agentFee: 0,
    deliveryFee: 0,
    total: 16600,
    payment: { method: "Wallet" },
    delivery: { method: "Ojarun delivery", address: "19 Ogunlana Drive, Surulere, Lagos", estimatedTime: "25 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Mile 12 Market",
  },
  {
    orderId: "ORD-019",
    date: "2026-04-02",
    status: "failed",
    items: [
      { id: "1", name: "Egusi (Melon Seeds)", quantity: 4, unit: "Per kg", price: 3500, image: "/assets/productPlaceholder.png" },
      { id: "7", name: "Long Grain Rice", quantity: 2, unit: "Per kg", price: 5200, image: "/assets/productPlaceholder.png" },
      { id: "9", name: "Honey Beans (Oloyin)", quantity: 1, unit: "Per kg", price: 4500, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 28900,
    agentFee: 0,
    deliveryFee: 0,
    total: 28900,
    payment: { method: "Visa", maskedCard: "******6187" },
    delivery: { method: "Ojarun delivery", address: "11 Idowu Martins Street, Victoria Island, Lagos", estimatedTime: "20 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
  {
    orderId: "ORD-020",
    date: "2026-05-12",
    status: "failed",
    items: [
      { id: "16", name: "Milo (Tinned)", quantity: 5, unit: "Per tin", price: 3200, image: "/assets/productPlaceholder.png" },
      { id: "17", name: "Peak Milk", quantity: 1, unit: "Per carton", price: 4500, image: "/assets/productPlaceholder.png" },
      { id: "15", name: "Corn Flakes", quantity: 3, unit: "Per pack", price: 1800, image: "/assets/productPlaceholder.png" },
    ],
    subtotal: 25900,
    agentFee: 0,
    deliveryFee: 0,
    total: 25900,
    payment: { method: "Cash" },
    delivery: { method: "Ojarun delivery", address: "8 Adeola Odeku Street, Victoria Island, Lagos", estimatedTime: "15 Mins" },
    timeline: { orderReceived: true, shoppingInProgress: false, readyForPickup: false, delivered: false },
    market: "Ojarun Market",
  },
];

export const MOCK_NOTIFICATIONS: NotificationProps[] = [
  {
    type: "order",
    title: "Order Confirmed",
    message: "Your order ORD-001 has been confirmed and is being processed",
    isRead: true,
  },
  {
    type: "order",
    title: "Order Delivered",
    message: "Your order ORD-003 has been delivered successfully",
    isRead: true,
  },
  {
    type: "order",
    title: "Shopping In Progress",
    message: "Your order ORD-009 is currently being shopped for",
    isRead: false,
  },
  {
    type: "order",
    title: "Ready for Pickup",
    message: "Your order ORD-012 is ready for pickup at Ojarun Market",
    isRead: false,
  },
  {
    type: "promotion",
    title: "Weekend Flash Sale",
    message: "Get 20% off on all grains this weekend only",
    isRead: true,
  },
  {
    type: "promotion",
    title: "New Arrivals",
    message: "Fresh catfish and stockfish just arrived at Mile 12 Market",
    isRead: false,
  },
  {
    type: "promotion",
    title: "Refer & Earn",
    message: "Invite a friend and earn ₦500 on their first order",
    isRead: false,
  },
  {
    type: "profile",
    title: "Welcome to Ojarun",
    message: "Thanks for joining! Complete your profile for faster checkout",
    isRead: true,
  },
  {
    type: "profile",
    title: "Payment Method Added",
    message: "Your Mastercard ****4832 has been successfully linked",
    isRead: true,
  },
  {
    type: "profile",
    title: "Account Update",
    message: "Your delivery address has been updated successfully",
    isRead: false,
  },
];

export const mockMeals: Meal[] = [
  {
    id: "meal-1",
    name: "Egusi Soup",
    imageURL: "/assets/images/meals/egusi.jpg",
    description: "Traditional egusi soup ingredients bundle.",
    servings: "serves 4-5",
    totalPrice: 7300,
    ingredients: [
      {
        product: {
          id: "prod-1",
          name: "Egusi",
          category: "Seeds",
          price: 1000,
          imageURL: "/assets/images/products/egusi.jpg",
          unit: "Per derica",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-2",
          name: "Ugu Leaves",
          category: "Vegetables",
          price: 300,
          imageURL: "/assets/images/products/ugu.jpg",
          unit: "Per bunch",
        },
        quantity: 2,
      },
      {
        product: {
          id: "prod-3",
          name: "Palm Oil",
          category: "Oil",
          price: 1800,
          imageURL: "/assets/images/products/palm-oil.jpg",
          unit: "Per bottle",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-4",
          name: "Pepper Mix",
          category: "Spices",
          price: 700,
          imageURL: "/assets/images/products/pepper.jpg",
          unit: "Per pack",
        },
        quantity: 1,
      },
    ],
  },

  {
    id: "meal-2",
    name: "Jollof Rice",
    imageURL: "/assets/images/meals/jollof-rice.jpg",
    description: "Everything needed for delicious Nigerian jollof rice.",
    servings: "serves 5-6",
    totalPrice: 6500,
    ingredients: [
      {
        product: {
          id: "prod-5",
          name: "Rice",
          category: "Grains",
          price: 2500,
          imageURL: "/assets/images/products/rice.jpg",
          unit: "Per 5kg",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-6",
          name: "Fresh Tomatoes",
          category: "Vegetables",
          price: 800,
          imageURL: "/assets/images/products/tomatoes.jpg",
          unit: "Per basket",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-7",
          name: "Onions",
          category: "Vegetables",
          price: 500,
          imageURL: "/assets/images/products/onion.jpg",
          unit: "Per bag",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-8",
          name: "Vegetable Oil",
          category: "Oil",
          price: 1700,
          imageURL: "/assets/images/products/vegetable-oil.jpg",
          unit: "Per bottle",
        },
        quantity: 1,
      },
    ],
  },

  {
    id: "meal-3",
    name: "Spaghetti Stir Fry",
    imageURL: "/assets/images/meals/spaghetti.jpg",
    description: "Quick and tasty spaghetti stir fry ingredients.",
    servings: "serves 3-4",
    totalPrice: 5200,
    ingredients: [
      {
        product: {
          id: "prod-9",
          name: "Spaghetti",
          category: "Pasta",
          price: 1200,
          imageURL: "/assets/images/products/spaghetti.jpg",
          unit: "Per pack",
        },
        quantity: 2,
      },
      {
        product: {
          id: "prod-6",
          name: "Fresh Tomatoes",
          category: "Vegetables",
          price: 800,
          imageURL: "/assets/images/products/tomatoes.jpg",
          unit: "Per basket",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-10",
          name: "Carrots",
          category: "Vegetables",
          price: 400,
          imageURL: "/assets/images/products/carrots.jpg",
          unit: "Per bunch",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-7",
          name: "Onions",
          category: "Vegetables",
          price: 500,
          imageURL: "/assets/images/products/onion.jpg",
          unit: "Per bag",
        },
        quantity: 1,
      },
    ],
  },

  {
    id: "meal-4",
    name: "Chocolate Cake",
    imageURL: "/assets/images/meals/chocolate-cake.jpg",
    description: "Baking ingredients for a rich chocolate cake.",
    servings: "serves 8-10",
    totalPrice: 9800,
    ingredients: [
      {
        product: {
          id: "prod-11",
          name: "Flour",
          category: "Baking",
          price: 1800,
          imageURL: "/assets/images/products/flour.jpg",
          unit: "Per bag",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-12",
          name: "Sugar",
          category: "Baking",
          price: 1200,
          imageURL: "/assets/images/products/sugar.jpg",
          unit: "Per bag",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-13",
          name: "Cocoa Powder",
          category: "Baking",
          price: 1500,
          imageURL: "/assets/images/products/cocoa.jpg",
          unit: "Per pack",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-14",
          name: "Eggs",
          category: "Dairy",
          price: 2000,
          imageURL: "/assets/images/products/eggs.jpg",
          unit: "Per crate",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-15",
          name: "Butter",
          category: "Dairy",
          price: 1800,
          imageURL: "/assets/images/products/butter.jpg",
          unit: "Per pack",
        },
        quantity: 1,
      },
    ],
  },

  {
    id: "meal-5",
    name: "Fried Rice",
    imageURL: "/assets/images/meals/fried-rice.jpg",
    description: "Fresh ingredients bundle for classic fried rice.",
    servings: "serves 5-6",
    totalPrice: 7800,
    wishlisted: true,
    ingredients: [
      {
        product: {
          id: "prod-5",
          name: "Rice",
          category: "Grains",
          price: 2500,
          imageURL: "/assets/images/products/rice.jpg",
          unit: "Per 5kg",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-10",
          name: "Carrots",
          category: "Vegetables",
          price: 400,
          imageURL: "/assets/images/products/carrots.jpg",
          unit: "Per bunch",
        },
        quantity: 2,
      },
      {
        product: {
          id: "prod-16",
          name: "Green Peas",
          category: "Vegetables",
          price: 700,
          imageURL: "/assets/images/products/peas.jpg",
          unit: "Per pack",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-17",
          name: "Sweet Corn",
          category: "Vegetables",
          price: 800,
          imageURL: "/assets/images/products/corn.jpg",
          unit: "Per can",
        },
        quantity: 1,
      },
      {
        product: {
          id: "prod-18",
          name: "Chicken",
          category: "Protein",
          price: 2500,
          imageURL: "/assets/images/products/chicken.jpg",
          unit: "Per kg",
        },
        quantity: 1,
      },
    ],
  },
];

export const DEMO_SHOPPING_LISTS: ShoppingList[] = [
  {
    id: "list-1",
    name: "Weekly Family Shopping",
    items: [
      { name: "Egusi (Melon Seeds)", price: 3500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
      { name: "Long Grain Rice", price: 5200, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 5 },
      { name: "Palm Oil", price: 3200, imageURL: "/assets/Untitled design.png", more: "Per bottle", quantity: 3 },
      { name: "Garri (White)", price: 2500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
      { name: "Honey Beans (Oloyin)", price: 4500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 1 },
      { name: "Dried Stockfish", price: 8500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 1 },
      { name: "Groundnut Oil", price: 3800, imageURL: "/assets/Untitled design.png", more: "Per bottle", quantity: 1 },
    ],
    updatedAt: "3 days ago",
  },
  {
    id: "list-2",
    name: "Jollof Rice Party Prep",
    items: [
      { name: "Long Grain Rice", price: 5200, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 5 },
      { name: "Groundnut Oil", price: 3800, imageURL: "/assets/Untitled design.png", more: "Per bottle", quantity: 2 },
      { name: "Ofada Rice", price: 5800, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 3 },
    ],
    updatedAt: "1 week ago",
  },
  {
    id: "list-3",
    name: "Mom's Soup Run",
    items: [
      { name: "Egusi (Melon Seeds)", price: 3500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 3 },
      { name: "Ogbono (Dried)", price: 4000, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
      { name: "Dried Stockfish", price: 8500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 1 },
      { name: "Palm Oil", price: 3200, imageURL: "/assets/Untitled design.png", more: "Per bottle", quantity: 2 },
      { name: "Smoked Catfish", price: 6000, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 1 },
    ],
    updatedAt: "5 days ago",
  },
  {
    id: "list-4",
    name: "Breakfast Staples",
    items: [
      { name: "Garri (White)", price: 2500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 3 },
      { name: "Garri (Yellow)", price: 2700, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
      { name: "Honey Beans (Oloyin)", price: 4500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
    ],
    updatedAt: "2 weeks ago",
  },
  {
    id: "list-5",
    name: "Protein Stock-Up",
    items: [
      { name: "Smoked Catfish", price: 6000, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 4 },
      { name: "Dried Stockfish", price: 8500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 3 },
      { name: "Honey Beans (Oloyin)", price: 4500, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 5 },
      { name: "Ogbono (Dried)", price: 4000, imageURL: "/assets/Untitled design.png", more: "Per kg", quantity: 2 },
    ],
    updatedAt: "1 day ago",
  },
];